
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msusers
    username: root
    password: root


  application:
    name: USER-SERVICE

#  profiles:
#    active: dev

  config:
    import: optional:configserver:http://localhost:8085  # fetching config from server



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect






#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

